nec:
  jwtExpirationMs: 86400000
  jwtSecret: FnCYIx1G7Xlo7eaRKQVlMNUlwYxHuvyhXJrBHJpCfZhPOiXAhBfKFNKGQVnvhtnshrrJLigw1HWZQ6LAgMBAAE==
spring:
  main:
    banner-mode: off
  application:
    name: National Electric Company
  datasource:
    url: ${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver 
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  mvc:
    servlet:
      path: /api
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect